### ISSUE TITLE
Xcode12 can't open the project file, can it support iOS14.x?

### ISSUE THREAD

**Issue by fhefh2015** [dheerajghub/Quotes-App#1]

**Comment by dheerajghub** [comment]
Hi fhefh2015,
Yeah I get your point, actually, I'm building this application in Xcode 13 so you've probably had to change its project compatible version in your Xcode: you can take a reference from StackOverflow here is a link , https://stackoverflow.com/questions/49622341/failed-to-load-project-incompatible-project-version-pop-up-appears-when-i-op and do let me know once its resolved!
